
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
module Top_Module(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);
/* VGA test inputs: declare signals and generate simple patterns per FSM state
   - `next_x`/`next_y` come from `vga_driver` and are used to generate pixels
   - `color_in` format: RRRGGGBB
*/
wire vga_clk;
wire clk_1hz;
wire clk_60hz; // shared 60Hz clock for game logic and other slow logic
wire [9:0] next_x;
wire [9:0] next_y;
wire [9:0] p1_current_x;
wire [9:0] p2_current_x;
wire [9:0] p1_def_hurt_x;
wire [9:0] p1_def_hurt_y;
wire [9:0] p1_def_hurt_w;
wire [9:0] p1_def_hurt_h;
wire [9:0] p1_def_rec_hurt_x;
wire [9:0] p1_def_rec_hurt_y;
wire [9:0] p1_def_rec_hurt_w;
wire [9:0] p1_def_rec_hurt_h;
wire [9:0] p1_atk_hit_x;
wire [9:0] p1_atk_hit_y;
wire [9:0] p1_atk_hit_w;
wire [9:0] p1_atk_hit_h;
wire [9:0] p2_def_hurt_x;
wire [9:0] p2_def_hurt_y;
wire [9:0] p2_def_hurt_w;
wire [9:0] p2_def_hurt_h;
wire [9:0] p2_def_rec_hurt_x;
wire [9:0] p2_def_rec_hurt_y;
wire [9:0] p2_def_rec_hurt_w;
wire [9:0] p2_def_rec_hurt_h;
wire [9:0] p2_atk_hit_x;
wire [9:0] p2_atk_hit_y;
wire [9:0] p2_atk_hit_w;
wire [9:0] p2_atk_hit_h;
wire [7:0] p1_charge_value;
wire [7:0] p2_charge_value;
reg  [7:0] comb_color;       // selected color before registering
reg  [7:0] color_in_reg;     // registered color sampled by VGA driver
reg  [7:0] color_in1, color_in2, color_in3, color_in4;
reg [2:0] start_step; // increments each second during START

// HEX label wires for P1/P2 in START/GAME and MENU when players are opposite
wire [2:0] hex0_val, hex1_val, hex2_val, hex3_val, hex4_val, hex5_val;
wire [6:0] hex0_seg, hex1_seg, hex2_seg, hex3_seg, hex4_seg, hex5_seg;

wire menu_hex_active = (game_fsm_state == MENU) && (green_left_side != blue_left_side);
// Debug override: set SW[8]=1 to force HEX labels on for debugging
wire debug_force_hex = SW[8];
wire hex_p_labels_active = debug_force_hex || (game_fsm_state == START) || (game_fsm_state == GAME) || menu_hex_active;
wire hex_vs_active = debug_force_hex || (game_fsm_state == START) || (game_fsm_state == GAME);
wire left_side_is_p2 = green_left_side;
wire right_side_is_p2 = ~green_left_side;

wire [9:0] digit_x_start = 10'd304; // 32 px wide (8*4) centered-ish
wire [9:0] digit_y_start = 10'd200; // vertical position
wire in_digit_bounds = (next_x >= digit_x_start) && (next_x < digit_x_start + 10'd32) &&
					   (next_y >= digit_y_start) && (next_y < digit_y_start + 10'd48);
wire [2:0] digit_small_x = (next_x - digit_x_start) >> 2;
wire [3:0] digit_small_y = (next_y - digit_y_start) >> 2;

// START word positioning (48x12)
wire [9:0] start_x = 10'd236; // center roughly (236 + 48/2 ~260)
wire [9:0] start_y = 10'd220;
wire in_start_bounds = (next_x >= start_x) && (next_x < start_x + 10'd48) &&
					  (next_y >= start_y) && (next_y < start_y + 10'd12);
wire [5:0] start_small_x = next_x - start_x;
wire [3:0] start_small_y = next_y - start_y;

// Per-state combinational patterns (computed from driver-provided next_x/next_y)
// Additional signals for MENU visuals (shared with top_vga_menu)
reg [1:0] green_btn_reg;
reg [1:0] blue_btn_reg;
reg green_left_side;
reg blue_left_side;
wire reset_vga = ~GPIO[3];

// Dynamic X Coordinate Constants for the indicators
wire [9:0] left_side_x  = 10'd110;
wire [9:0] right_side_x = 10'd480;
wire [9:0] green_x = green_left_side ? left_side_x : right_side_x;
wire [9:0] blue_x  = blue_left_side  ? left_side_x : right_side_x;

// MENU layout constants and ROM addressing
wire [9:0] menu_start_x = 10'd160;
wire [9:0] menu_start_y = 10'd40;
wire in_menu_bounds = (next_x >= menu_start_x) && (next_x < menu_start_x + 10'd320) &&
					  (next_y >= menu_start_y) && (next_y < menu_start_y + 10'd96);
wire [5:0] menu_rom_x = (next_x - menu_start_x) >> 3;
wire [3:0] menu_rom_y = (next_y - menu_start_y) >> 3;
wire menu_on;

// P1 / P2 character areas (scaled 4x)
wire [9:0] p1_start_x = (game_fsm_state == GAME) ? p1_current_x : 10'd100;
wire [9:0] p1_start_y = (game_fsm_state == GAME) ? 10'd240 : 10'd100;
wire in_p1_bounds = (next_x >= p1_start_x) && (next_x < p1_start_x + 10'd72) &&
				(next_y >= p1_start_y) && (next_y < p1_start_y + 10'd48);
wire [4:0] p1_rom_x = (next_x - p1_start_x) >> 2;
wire [3:0] p1_rom_y = (next_y - p1_start_y) >> 2;
wire p1_on;

wire [9:0] p2_start_x = (game_fsm_state == GAME) ? p2_current_x : 10'd470;
wire [9:0] p2_start_y = (game_fsm_state == GAME) ? 10'd240 : 10'd100;
wire in_p2_bounds = (next_x >= p2_start_x) && (next_x < p2_start_x + 10'd72) &&
					(next_y >= p2_start_y) && (next_y < p2_start_y + 10'd48);


//	p2 char rom
wire [4:0] p2_rom_x = (next_x - p2_start_x) >> 2;
wire [3:0] p2_rom_y = (next_y - p2_start_y) >> 2;

wire p2_on;

// Backward input indicator (on-screen debug)
wire in_bwd_indicator = p1_bwd | p2_bwd;
wire in_bwd_rect = (next_x >= 10'd10) && (next_x < 10'd30) && (next_y >= 10'd10) && (next_y < 10'd30);

//	MENU screen boxes
wire in_green_rect = (next_x >= green_x) && (next_x < green_x + 10'd50) && (next_y >= 10'd320) && (next_y < 10'd340);
wire in_blue_rect  = (next_x >= blue_x)  && (next_x < blue_x + 10'd50)  && (next_y >= 10'd360) && (next_y < 10'd380);
// Hitbox ve Hurtbox rectangles
wire in_p1_def_hurt = (next_x >= p1_def_hurt_x) && (next_x < p1_def_hurt_x + p1_def_hurt_w) && (next_y >= p1_def_hurt_y) && (next_y < p1_def_hurt_y + p1_def_hurt_h);
wire in_p1_atk_hit  = (next_x >= p1_atk_hit_x)  && (next_x < p1_atk_hit_x  + p1_atk_hit_w)  && (next_y >= p1_atk_hit_y)  && (next_y < p1_atk_hit_y  + p1_atk_hit_h);

wire in_p2_def_hurt = (next_x >= p2_def_hurt_x) && (next_x < p2_def_hurt_x + p2_def_hurt_w) && (next_y >= p2_def_hurt_y) && (next_y < p2_def_hurt_y + p2_def_hurt_h);
wire in_p2_atk_hit  = (next_x >= p2_atk_hit_x)  && (next_x < p2_atk_hit_x  + p2_atk_hit_w)  && (next_y >= p2_atk_hit_y)  && (next_y < p2_atk_hit_y  + p2_atk_hit_h);

wire [9:0] charge_bar_width = 10'd30;
wire [9:0] charge_bar_height = 10'd8;

wire [9:0] p1_charge_bar_x = p1_start_x + 10'd21;
wire [9:0] p1_charge_bar_y = p1_start_y - 10'd12;

wire [9:0] p2_charge_bar_x = p2_start_x + 10'd21;
wire [9:0] p2_charge_bar_y = p2_start_y - 10'd12;
wire [9:0] p1_charge_fill_width = (p1_charge_value) / 10'd4; // Scale 0-120 to 0-30 for the bar
wire [9:0] p2_charge_fill_width = (p2_charge_value) / 10'd4; // Scale 0-120 to 0-30 for the bar	
wire in_p1_charge_bar_bg = (game_fsm_state == GAME) && (next_x >= p1_charge_bar_x) && (next_x < p1_charge_bar_x + charge_bar_width) &&
                            (next_y >= p1_charge_bar_y) && (next_y < p1_charge_bar_y + charge_bar_height);
wire in_p1_charge_bar_fill = in_p1_charge_bar_bg && (next_x < p1_charge_bar_x + p1_charge_fill_width);
wire in_p2_charge_bar_bg = (game_fsm_state == GAME) && (next_x >= p2_charge_bar_x) && (next_x < p2_charge_bar_x + charge_bar_width) &&
                            (next_y >= p2_charge_bar_y) && (next_y < p2_charge_bar_y + charge_bar_height);
wire in_p2_charge_bar_fill = in_p2_charge_bar_bg && (next_x < p2_charge_bar_x + p2_charge_fill_width);

// Instantiate menu and p ROMs
// MENU P1 P2 and START ROMs
menu menu_rom_inst (.x(menu_rom_x), .y(menu_rom_y), .menu_on(menu_on));
p p1_rom_inst (.x(p1_rom_x), .y(p1_rom_y), .select_p2(1'b0), .pixel_on(p1_on));
p p2_rom_inst (.x(p2_rom_x), .y(p2_rom_y), .select_p2(1'b1), .pixel_on(p2_on));
digit_3 d3_inst(.x(digit_small_x), .y(digit_small_y), .pixel_on(d3_on));
digit_2 d2_inst(.x(digit_small_x), .y(digit_small_y), .pixel_on(d2_on));
digit_1 d1_inst(.x(digit_small_x), .y(digit_small_y), .pixel_on(d1_on));
start start_inst(.x(start_small_x), .y(start_small_y), .pixel_on(start_on));

// HEX segment drivers for P1/P2 labels
P7seg hex0_seg_inst(.hex(hex0_val), .hexn(hex0_seg));
P7seg hex1_seg_inst(.hex(hex1_val), .hexn(hex1_seg));
P7seg hex2_seg_inst(.hex(hex2_val), .hexn(hex2_seg));
P7seg hex3_seg_inst(.hex(hex3_val), .hexn(hex3_seg));
P7seg hex4_seg_inst(.hex(hex4_val), .hexn(hex4_seg));
P7seg hex5_seg_inst(.hex(hex5_val), .hexn(hex5_seg));

assign HEX0 = hex_p_labels_active ? hex0_seg : 7'b1111111;
assign HEX1 = hex_p_labels_active ? hex1_seg : 7'b1111111;
assign HEX4 = hex_p_labels_active ? hex4_seg : 7'b1111111;
assign HEX5 = hex_p_labels_active ? hex5_seg : 7'b1111111;
assign HEX2 = hex_vs_active ? hex2_seg : 7'b1111111;
assign HEX3 = hex_vs_active ? hex3_seg : 7'b1111111;

// Button synchronization and toggle logic (use vga_clk as 25MHz)
always @(posedge vga_clk or posedge reset_vga) begin
    if (reset_vga) begin
        green_btn_reg <= 2'b11;
        blue_btn_reg  <= 2'b11;
        green_left_side <= 1'b1;
        blue_left_side  <= 1'b0;
    end else begin
        green_btn_reg <= {green_btn_reg[0], KEY[1]};
        blue_btn_reg  <= {blue_btn_reg[0],  KEY[2]};
        
        // Allow em use KEY 0&1 in only MENU state to change character side selection
        if (green_btn_reg == 2'b10 && game_fsm_state == MENU) green_left_side <= ~green_left_side;
        if (blue_btn_reg  == 2'b10 && game_fsm_state == MENU) blue_left_side  <= ~blue_left_side;
    end
end


assign hex5_val = 7'b00011000; // 'P'
assign hex4_val = left_side_is_p2 ? 3'd2 : 3'd1; // left side shows P2 if green is left, otherwise P1
assign hex1_val = 7'b00011000; // 'P'
assign hex0_val = right_side_is_p2 ? 3'd2 : 3'd1; // right side shows P2 if green is right, otherwise P1
assign hex2_val = p1_state; // 'V'
assign hex3_val = p2_state; // 'S'

always @(*) begin
    // START State Logic
    if (game_fsm_state == START) begin
        if (in_digit_bounds) begin
            case (start_step)
                3'd0: color_in2 = d3_on ? 8'b111_000_00 : 8'b000_000_00;
                3'd1: color_in2 = d2_on ? 8'b111_000_00 : 8'b000_000_00;
                3'd2: color_in2 = d1_on ? 8'b111_000_00 : 8'b000_000_00;
                default: color_in2 = 8'b000_000_00;
            endcase
        end else if (start_step == 3 && in_start_bounds) begin
            color_in2 = start_on ? 8'b111_000_00 : 8'b000_000_00;
        end else begin
            color_in2 = 8'b000_000_00;
        end
    end else begin
        // Clear start screen background area when not in START state
        color_in2 = (next_y >= 10'd200 && next_y < 10'd280) ? 8'b000_111_00 : 8'b000_000_00;
    end
    
    // Default colors for other states
    color_in3 = ((next_x >= 10'd100 && next_x < 10'd300 && next_y >= 10'd100 && next_y < 10'd200) ? 8'b111_000_00 : 8'b000_000_00);
    color_in4 = 8'b111_111_11;

    // MENU, GAME, and END State Logic
    if (game_fsm_state == MENU) begin
        if (in_menu_bounds && menu_on) begin
            color_in1 = 8'b111_000_00; // Menu text (Red)
        end else if (in_p1_bounds && p1_on) begin
            color_in1 = 8'b111_000_00; // P1 sprite on menu (Red)
        end else if (in_p2_bounds && p2_on) begin
            color_in1 = 8'b000_000_11; // P2 sprite on menu (Blue)
        end else if (in_green_rect) begin
            color_in1 = 8'b000_111_00; // Green selection indicator
        end else if (in_blue_rect) begin
            color_in1 = 8'b000_000_11; // Blue selection indicator
        end else begin
            color_in1 = 8'b001_001_01; // Dark gray background for menu
        end
        
    end else if (game_fsm_state == GAME) begin
        if (in_p1_charge_bar_fill) begin
            color_in1 = 8'b000_111_00; // P1 charge fill (green)
        end else if (in_p1_charge_bar_bg) begin
            color_in1 = 8'b011_011_01; // P1 charge bar background (gray)
        end else if (in_p2_charge_bar_fill) begin
            color_in1 = 8'b000_111_00; // P2 charge fill (green)
        end else if (in_p2_charge_bar_bg) begin
            color_in1 = 8'b011_011_01; // P2 charge bar background (gray)
        end else if (in_p1_bounds) begin
            color_in1 = 8'b111_000_00; // P1 main body (Solid Red)
        end else if (in_p2_bounds) begin
            color_in1 = 8'b000_000_11; // P2 main body (Solid Blue)
        end else if (in_p1_atk_hit) begin
            color_in1 = 8'b111_111_00; // P1 attack hitbox (Solid Yellow)
        end else if (in_p1_def_hurt) begin
            color_in1 = 8'b111_001_00; // P1 defensive hurtbox (Solid Orange)
        end else if (in_p2_atk_hit) begin
            color_in1 = 8'b000_111_11; // P2 attack hitbox (Solid Cyan)
        end else if (in_p2_def_hurt) begin
            color_in1 = 8'b001_111_11; // P2 defensive hurtbox (Solid Light Cyan)
        end else if (next_y >= 10'd320) begin
            color_in1 = 8'b000_111_00; // Ground (Green)
        end else begin
            color_in1 = 8'b001_001_01; // Game background (Dark Gray)
        end
        
    end else begin
        color_in1 = 8'b001_001_01; // Neutral background for END or undefined states
    end
end

// Select which per-state color to display
always @(*) begin
	case (game_fsm_state)
		MENU:  comb_color = color_in1;
		START: comb_color = color_in2;
		GAME:  comb_color = color_in1;
		END:   comb_color = color_in4;
		default: comb_color = 8'd0;
	endcase
end

// Register the selected color on the VGA clock to meet timing
always @(posedge vga_clk or posedge reset_vga) begin
	if (reset_vga)
		color_in_reg <= 8'd0;
	else
		color_in_reg <= comb_color;
end
// Instantiate prescalers for 1Hz, 60Hz, and VGA clock
prescaler #(.div_param(50000000)) clock_1hz(
		.clk(CLOCK_50),
		.out(clk_1hz)
	);
prescaler #(.div_param(2)) vga_clock(
        .clk(CLOCK_50),
        .out(vga_clk)
    );
prescaler #(.div_param(833333)) clock_60_hz(
        .clk(CLOCK_50),
        .out(clk_60hz)
    );
wire game_clk;
assign game_clk = (SW[8]) ? clk_60hz : ~KEY[3];
wire internal_rst_char_position;
wire [2:0] p1_state, p2_state;
wire [6:0] p1_frame, p2_frame;
wire [1:0] p1_block, p2_block;

game_logic game_logic_inst(
	.clk_60hz(game_clk),
	.clk_50(CLOCK_50),
	.rst(reset_vga | (game_fsm_state != GAME)),
	.p1_forward(p1_fwd),
	.p2_forward(p2_fwd),
	.p1_backward(p1_bwd),
	.p2_backward(p2_bwd),
	.p1_attack(p1_atk),
	.p2_attack(p2_atk),
	.p1_state(p1_state),
	.p2_state(p2_state),
	.p1_frame(p1_frame),
	.p2_frame(p2_frame),
	.p1_block(p1_block),
	.p2_block(p2_block),
	.p1_ko_num(p1_ko_num),
	.p2_ko_num(p2_ko_num),
	.p1_current_x(p1_current_x),
	.p2_current_x(p2_current_x),
	.p1_def_hurt_x(p1_def_hurt_x),
	.p1_def_hurt_y(p1_def_hurt_y),
	.p1_def_hurt_w(p1_def_hurt_w),
	.p1_def_hurt_h(p1_def_hurt_h),
	.p1_def_rec_hurt_x(p1_def_rec_hurt_x),
	.p1_def_rec_hurt_y(p1_def_rec_hurt_y),
	.p1_def_rec_hurt_w(p1_def_rec_hurt_w),
	.p1_def_rec_hurt_h(p1_def_rec_hurt_h),
	.p1_atk_hit_x(p1_atk_hit_x),
	.p1_atk_hit_y(p1_atk_hit_y),
	.p1_atk_hit_w(p1_atk_hit_w),
	.p1_atk_hit_h(p1_atk_hit_h),
	.p1_charge_value(p1_charge_value),
	.p2_charge_value(p2_charge_value),
	.p2_def_hurt_x(p2_def_hurt_x),
	.p2_def_hurt_y(p2_def_hurt_y),
	.p2_def_hurt_w(p2_def_hurt_w),
	.p2_def_hurt_h(p2_def_hurt_h),
	.p2_def_rec_hurt_x(p2_def_rec_hurt_x),
	.p2_def_rec_hurt_y(p2_def_rec_hurt_y),
	.p2_def_rec_hurt_w(p2_def_rec_hurt_w),
	.p2_def_rec_hurt_h(p2_def_rec_hurt_h),
	.p2_atk_hit_x(p2_atk_hit_x),
	.p2_atk_hit_y(p2_atk_hit_y),
	.p2_atk_hit_w(p2_atk_hit_w),
	.p2_atk_hit_h(p2_atk_hit_h),
	.internal_rst_char_position(internal_rst_char_position)
);

localparam [1:0] MENU = 2'b00;
localparam [1:0] START = 2'b01;
localparam [1:0] GAME = 2'b10;
localparam [1:0] END = 2'b11;

// START-second step counter (advances at 1Hz)
always @(posedge clk_1hz or posedge reset_vga) begin
	if (reset_vga)
		start_step <= 3'd0;
	else if (game_fsm_state == START)
		start_step <= start_step + 3'd1;
	else
		start_step <= 3'd0;
end

reg [2:0] game_fsm_state, game_fsm_next_state;//MENU,START,GAME,END
wire [1:0] p1_ko_num, p2_ko_num;

always @(*) begin
	game_fsm_next_state = game_fsm_state;
	// state transitions
	case (game_fsm_state)
		MENU: begin
			// Transition to START if indicators on opposite sides and appropriate SW is pressed
			// If green is on left: check SW[0]; if blue is on left: check SW[1]
			//burası GPIO ile değişecek işte ikisi de fwd ve atk inputları olacak
			//henüz debuglayabilmek için bıraktım
			if (green_left_side != blue_left_side) begin
				if ((green_left_side && SW[0]) || (!green_left_side && SW[0])) begin
					game_fsm_next_state = START;
				end
			end
		end
		START: begin
			// Wait until the 1Hz start sequence completes (start_step >= 4)
			if (start_step >= 3'd4) game_fsm_next_state = GAME;
		end
		GAME: begin
			if (p1_ko_num == 3 || p2_ko_num == 3) begin
				game_fsm_next_state = END;
			end else begin
				game_fsm_next_state = GAME; // K.O. yoksa oyunda kalmaya devam et!
			end
		end
		END: begin
			//if(any P1 input) game_fsm_next_state = MENU;
		end
	endcase
end
reg p1_atk, p1_fwd, p1_bwd, p2_atk, p2_fwd, p2_bwd;
always @(*) begin//p1 p2 input değiş tokuş için GPIOların yarısı değişecek sonra KEY ile oynayacaksa bir kişi
	// default to inactive to avoid inferred latches
	p1_fwd  = 1'b0; p1_bwd = 1'b0; p1_atk = 1'b0;
	p2_fwd  = 1'b0; p2_bwd = 1'b0; p2_atk = 1'b0;

	// Map physical GPIO pins to logical player inputs according to orientation
	if (green_left_side) begin
		p1_fwd  = ~KEY[0];
		p1_bwd = ~KEY[1];
		p1_atk   = ~KEY[2];
		p2_fwd  = ~GPIO[9];
		p2_bwd = ~GPIO[5];
		p2_atk   = ~GPIO[7];
	end else begin
		p2_fwd  = ~KEY[1];
		p2_bwd = ~KEY[0];
		p2_atk   = ~KEY[2];
		p1_fwd  = ~GPIO[9];
		p1_bwd = ~GPIO[5];
		p1_atk   = ~GPIO[7];
	end
end
// Clock the FSM state on vga_clk
always @(posedge vga_clk or posedge reset_vga) begin
	if (reset_vga)
		game_fsm_state <= MENU;
	else
		game_fsm_state <= game_fsm_next_state;
end
	vga_driver vga_driver_inst(
	.clock(vga_clk),
	.reset(reset_vga),
	.color_in(color_in_reg),
	.next_x(next_x),
	.next_y(next_y),
	.hsync(VGA_HS),
	.vsync(VGA_VS),
	.red(VGA_R),
	.green(VGA_G),
	.blue(VGA_B),
	.sync(VGA_SYNC_N),
	.clk(VGA_CLK),
	.blank(VGA_BLANK_N)
);


endmodule
